api/urls.py
from django import views
from django.urls import path, include
from . import serializer
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from . import views
from rest_framework.authtoken.views import obtain_auth_token
app_name='api'

urlpatterns = [
       path('token/', obtain_auth_token, name="api_token_auth"),
       path('sala-do-empreendedor/get-empresas/', views.Listar_Empresas.as_view()),
       path('cursos/get-interessados/<int:curso_id>/', views.AlunosInteressadosView.as_view(), name='listar_alunos_interessados'),
       path('cursos/get-cursos/', views.Listar_Cursos.as_view(), name='listar_cursos'),
]

cursos_empresariais/urls.py
from django.contrib import admin
from django.urls import path
from . import views
 
app_name='cursos_empresariais'
urlpatterns = [
    path('cursos/empresariais/', views.cursos, name='home'),
    path('cursos/empresariais/area-do-estudante/', views.area_do_estudante, name='area_do_estudante'),
    path('cursos/empresariais/editar-cadastro/', views.editar_cadastro, name='editar_cadastro'),
    path('cursos/empresariais/editar-senha/', views.alterar_senha, name='alterar_senha'),
    path('cursos/empresariais/editar-cadastro-pessoa/', views.editar_cadastro_pessoa, name='editar_cadastro_pessoa'),
    path('cursos/empresariais/atividade/<tipo>', views.cursos, name="cursos"),            
    path('cursos/empresariais/atividade/<tipo>/<filtro>', views.cursos_filtrado, name="filtrar"),            
    path('cursos/empresariais/atividade/<tipo>/<id>/detalhe', views.curso_detalhe, name="curso_detalhe"),            
    path('cursos/empresariais/atividade/<tipo>/<id>/matricular', views.matricular, name="matricula"),            
    # path('prematricula/', views.prematricula, name="prematricula"),
    path('cursos/empresariais/ensino-superior/', views.ensino_superior, name="ensino_superior"),
    path('cursos/empresariais/ensino-tecnico/', views.ensino_tecnico, name="ensino_tecnico"),
    path('cursos/empresariais/curriculo-vitae/', views.curriculo_vitae, name="curriculo_vitae"),
    path('cursos/profissionais/empresariais/exportar_excel/', views.exportar_para_excel, name='exportar_excel'),
    path('capacitacao-empresarial/exportar_excel/por-turma/', views.exportar_para_excel_por_turma, name='exportar_excel_por_turma'),

    #ADMINISTRATIVO
    path('admin/cursos/', views.administrativo, name="administrativo2"),

    path('admin/cursos/instiuicoes', views.adm_instituicoes_listar, name="adm_instituicoes_listar"),
    path('admin/cursos/instituicao/cadastrar', views.adm_instituicao_cadastrar, name="adm_cadastrar_instituicao"),
    path('admin/cursos/instituicao/<id>', views.adm_locais_editar, name="adm_editar_instituicao"),
    path('admin/cursos/instituicao/<id>/excluir', views.adm_locais_excluir, name="adm_locais_excluir"),
    # MISSING EDITAR 

    path('admin/cursos/locais', views.adm_locais_listar, name="adm_locais_listar"),
    path('admin/cursos/local/cadastrar', views.adm_locais_cadastrar, name="cadastrar_local"),
    path('admin/cursos/local/<id>/editar', views.adm_locais_editar, name="adm_locais_editar"),
    path('admin/cursos/locai/<id>/excluir', views.adm_locais_excluir, name="adm_locais_excluir"),
    # MISSING VISUALIZAR

    path('admin/cursos/categorias', views.adm_categorias_listar, name="adm_categorias_listar"),
    path('admin/cursos/categoria/cadastrar', views.adm_categorias_cadastrar, name="cadastrar_categoria"),
    path('admin/cursos/categoria/<id>/editar', views.adm_categorias_editar, name="adm_categorias_editar"),
    path('admin/cursos/categoria/<id>/excluir', views.adm_categorias_excluir, name="adm_categorias_excluir"),
    # MISSING VISUALIZAR

    path('admin/cursos/cursos', views.adm_cursos_listar, name="adm_cursos_listar"),
    path('admin/cursos/curso/cadastrar', views.adm_cursos_cadastrar, name="adm_cursos_cadastrar"),
    path('admin/cursos/curso/<id>/editar', views.adm_curso_editar, name="adm_curso_editar"),
    path('admin/cursos/curso/<id>/visualizar', views.adm_curso_visualizar, name="adm_curso_visualizar"),
    path('admin/cursos/cursos/<id>/detalhes', views.adm_curso_detalhes, name="adm_curso_detalhes"),
    path('admin/cursos/cursos<id>/detalhes/exportar_excel/', views.adm_cursos_interessados_excel, name='adm_cursos_interessados_excel'),
    # path('cursos/<id_curso>/remover-interessado/<id>/', views.remover_interessado, name="adm_remover_interessado"),
    path('remover-interessado/<id>/', views.remover_interessado, name="adm_remover_interessado"),
    # path('curso/<id>/requisito/criar', views.adm_curso_visualizar, name="adm_curso_visualizar"),


    # MISSING VISUALIZAR e EXCLUIR

    path('admin/cursos/instrutores', views.adm_professores_listar, name="adm_professores_listar"),        
    path('admin/cursos/instrutor/cadastrar', views.adm_professores_cadastrar, name="adm_professores_cadastrar"),
    path('admin/cursos/instrutor/<id>/editar', views.adm_professores_editar, name="adm_professores_editar"),
    path('admin/cursos/instrutor/<id>/excluir', views.adm_professores_excluir, name="adm_professores_excluir"),
    # MISSING VISUALIZAR

    # -------- Serve para confirmar um aluno selecionado, transformando seu status para "Aluno" -------- #
    path('admin/cursos/selecionado/<matricula>', views.visualizar_turma_selecionado, name="adm_turma_visualizar_selecionado"),
    # -------- # -------- #

    path('admin/cursos/turmas', views.adm_turmas_listar, name="adm_turmas_listar"),
    path('admin/cursos/turmas-encerradas', views.adm_turmas_listar_encerradas, name="adm_turmas_listar_encerradas"),
    path('admin/cursos/turma/cadastrar', views.adm_turmas_cadastrar, name="adm_turmas_cadastrar"),
    path('admin/cursos/turma/<id>', views.adm_turmas_visualizar, name="adm_turma_visualizar"),
    path('admin/cursos/turma/<id>/editar', views.visualizar_turma_editar, name="adm_turma_editar"),
    path('admin/cursos/turma/<id>/excluir', views.excluir_turma, name="adm_turma_excluir"),
    path('admin/cursos/turma/<id>/realocar', views.adm_realocar, name="adm_turma_realocar"),
    path('admin/cursos/turma/<id>/gerar-certificados', views.gerar_certificados, name="gerar_certificados"),

    path('admin/cursos/turma/<id>/turno/cadastrar', views.adm_turno_cadastrar, name="adm_turno_cadastrar"),
    # MISSING VISUALIZAR, EDITAR, LISTAR E EXCLUIR

    path('admin/cursos/turma/<turma_id>/aula/cadastrar', views.adm_aula_cadastrar, name="adm_aula_cadastrar"),
    path('admin/cursos/turma/<turma_id>/aulas', views.adm_aulas_listar, name="adm_aulas_listar"),
    path('admin/cursos/turma/<turma_id>/aula/<aula_id>', views.adm_aula_visualizar, name="adm_aula_visualizar"),
    # MISSING EDITAR E EXCLUIR

    
    path('admin/cursos/justificativa/<presenca_id>/cadastrar', views.adm_justificativa_cadastrar, name="adm_justificativa_cadastrar"),
    path('admin/cursos/justificativa/<presenca_id>', views.adm_justificativa_visualizar, name="adm_justificativa_visualizar"),
    # MISSING LISTAR, EDITAR E EXCLUIR

    # path('gambiarra/02', views.gambiarra_cevest, name="adm_gambiarra_alunos"),
    path('admin/cursos/alunos', views.adm_alunos_listar, name="adm_alunos_listar"),
    path('admin/cursos/alunos/cadastrar/', views.adm_cadastro_aluno, name="adm_cadastrar_aluno"),
    path('admin/cursos/aluno/<id>', views.adm_aluno_visualizar, name="adm_aluno_visualizar"),
    path('admin/cursos/aluno/<id>/editar', views.adm_aluno_editar, name="adm_aluno_editar"),
    path('admin/cursos/aluno/<id>/matricular/', views.matricular_aluno, name="adm_aluno_matricular"),
    path('admin/cursos/aluno/<matricula>/desmatricular', views.desmatricular_aluno, name="adm_desmatricular_aluno"),
    path('capacitacao-empresarial/retirar-duplicadas/', views.retirar_duplicadas, name='retirar_duplicadas'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('', include('desenvolve_nf.urls')),
    path('api/', include('api.urls')),
    path('ciencia-e-tecnologia/', include('cursos.urls')),    
    path('chat/', include('chat.urls')),
    path('sala-do-empreendedor/', include('sala_do_empreendedor.urls')),
    path('sala-do-empreendedor/', include('cursos_empresariais.urls')),
    path('sala-do-empreendedor/', include('cursos_profissionais.urls')),
    # path('senha-facil/', include('senhas_facil.urls')),
    path('administracao/', include('administracao.urls')),    
    path('django/', admin.site.urls),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cursos_empresariais/forms.py
import datetime
from time import strptime
from django import forms
from django.forms import ModelForm, ValidationError
from .models import *

class PasswordChangeCustomForm(forms.Form):
    old_password = forms.CharField(
        label="Senha atual",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    new_password1 = forms.CharField(
        label="Nova senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    new_password2 = forms.CharField(
        label="Repetir senha",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(PasswordChangeCustomForm, self).__init__(*args, **kwargs)

    def clean_old_password(self):
        old_password = self.cleaned_data.get("old_password")
        if not self.user.check_password(old_password):
            raise forms.ValidationError("Senha atual incorreta.")
        return old_password

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")
        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("As novas senhas não coincidem.")
        return cleaned_data

    def save(self):
        new_password = self.cleaned_data.get("new_password1")
        self.user.set_password(new_password)
        self.user.save()

class Aluno_form(ModelForm):

    class Meta:
        model = Aluno
        widgets = {
            'turmas': forms.CheckboxSelectMultiple(),
            'celular': forms.TextInput(attrs={'onkeydown': 'mascara(this, icelular)'}),
            'cep': forms.TextInput(attrs={'onkeydown': 'mascara(this, icep)'}),
            'cpf': forms.TextInput(attrs={'onkeydown': 'mascara(this, icpf)'}),
            'rg': forms.TextInput(attrs={'onkeydown': 'mascara(this, irg)'}),
            'dt_nascimento': forms.TextInput(attrs={'type': 'date'}),
            'disponibilidade': forms.CheckboxSelectMultiple(),   
            
            'aceita_mais_informacoes': forms.CheckboxInput(attrs={'required': True}),
            'li_e_aceito_termos': forms.CheckboxInput(attrs={'required': True}),

            'dt_nascimento': forms.widgets.DateInput(attrs={'type': 'date'}),
            'user_inclusao': forms.HiddenInput(),
            'user_ultima_alteracao': forms.HiddenInput(),
        }
            
        exclude = ['dt_inclusao', 'dt_alteracao', 'pessoa']


class CadastroProfessorForm(ModelForm):

    class Meta:
        model = Instrutor
        widgets = {
            'cpf': forms.TextInput(attrs={'onkeydown': 'mascara(this, icpf)'}),
            'celular': forms.TextInput(attrs={'onkeydown': 'mascara(this, icelular)'}),
        }
        exclude = ['dt_inclusao']


class CadastroCursoForm(ModelForm):

    class Meta:
        model = Curso
        widgets = {
            'dt_nascimento': forms.widgets.DateInput(attrs={'type': 'date'}),
        }
        exclude = ['dt_inclusao', 'dt_alteracao', 'user_inclusao']

    def clean_sigla(self):
        sigla = self.cleaned_data['sigla']


        if not sigla.isalpha():
            raise ValidationError("A sigla deve conter apenas letras")
        
        return sigla.capitalize()


class CadastroTurmaForm(ModelForm):

    class Meta:
        model = Turma
        widgets = {
            'data_inicio': forms.TextInput(attrs={'type': 'date'}),
            'data_final': forms.TextInput(attrs={'type': 'date'}),
            'instrutores': forms.CheckboxSelectMultiple(),
            'disponibilidade': forms.CheckboxSelectMultiple(),
            
        }
        exclude = ['dt_inclusao', 'dt_alteracao', 'turnos', 'nome', 'user_ultima_alteracao', 'user_inclusao']


class CadastroCategoriaForm(ModelForm):

    class Meta:
        model = Categoria
        exclude = []


class CadastroLocalForm(ModelForm):

    class Meta:
        model = Local
        widgets = {
            'ativo': forms.HiddenInput(),
            'cep': forms.TextInput(attrs={'onkeydown': 'mascara(this, icep)'}),
        }
        exclude = []


class CadastroAlunoForm(ModelForm):

    class Meta:
        model = Aluno
        widgets = {
            'celular': forms.TextInput(attrs={'onkeydown': 'mascara(this, icelular)'}),
            'dt_nascimento': forms.TextInput(attrs={'type': 'date'}),
            'cpf': forms.TextInput(attrs={'onkeydown': 'mascara(this, icpf)'}),

        }
        exclude = []


class CadastroResponsavelForm(ModelForm):

    class Meta:
        model = Responsavel
        widgets = {
            'celular': forms.TextInput(attrs={'onkeydown': 'mascara(this, icelular)'}),
            'dt_nascimento': forms.TextInput(attrs={'type': 'date'}),
            'cep': forms.TextInput(attrs={'onkeydown': 'mascara(this, icep)'}),
            'rg': forms.TextInput(attrs={'onkeydown': 'mascara(this, irg)'}),
            'cpf': forms.TextInput(attrs={'onkeydown': 'mascara(this, icpf)'}),

        }
        exclude = ['aluno']

class Instituicao_form(ModelForm):

    class Meta:
        model = Instituicao
        exclude = []

    def clean_sigla(self):
        sigla = self.cleaned_data['sigla']


        if not sigla.isalpha():
            raise ValidationError("A sigla deve conter apenas letras")
        
        return sigla.capitalize()

class Turno_form(ModelForm):

    class Meta:
        model=Turno
        exclude = []


class ChoiceField_no_validation(forms.ChoiceField):
    def validate(self, value):
        """Validate that the input is in self.choices."""
        
    def valid_value(self, value):
        """Check to see if the provided value is a valid choice."""
        return True
    
    def to_python(self, value):
        return Turno_estabelecido.objects.get(pk=value)
        
class Aula_form(ModelForm):

    class Meta:
        model=Aula
        exclude = []
    
    associacao_turma_turno = ChoiceField_no_validation(label='Turno', choices=[])
    dt_aula = forms.DateField(label='Data da aula',widget=forms.DateInput(attrs={'type': 'date'}))


    def clean_dt_aula(self):
        dt_aula = self.cleaned_data['dt_aula']
        associacao_turma_turno = self.cleaned_data['associacao_turma_turno']

        if int(associacao_turma_turno.turno.dia_semana) != (dt_aula.weekday() + 1) % 7 + 1:
            raise ValidationError("Dia da semana da aula não corresponde com o turno")

        return dt_aula 
    

class Justificativa_form(ModelForm):

    class Meta:
        model=Justificativa
        exclude = []

    descricao = forms.CharField(widget=forms.Textarea)

#forms para matricular aluno em uma turma
class MatriculaAlunoForm(ModelForm):
    
    class Meta:
        model = Matricula
        widgets = {
            'turma': forms.Select(attrs={'class': 'form-control'}),
            'aluno': forms.HiddenInput(),
        }
        fields = ['turma', 'aluno','status']

cursos_empresariais/templates/adm/instituicoes/adm_instituicao_cadastrar.html
{% extends 'template.html' %}
{% load bootstrap5 %}
{% load static%}
{% block title %}BEM VINDO - CURSOS LIVRES{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/administrativo.css' %}">

{% endblock %}
{% block nav %}
{% include 'nav_empreendedor.html' %}
{% endblock %}
{% block administrativo %}fw-bold{% endblock %}
{% block main %}
<div class="row">
    <div class="col d-flex py-5"> 
        <div class="row w-100">
            <div class="col-10 pb-4 m-auto bg-white">
                             
                <div class="row">
                    <div class="col text-dark px-4 pt-4">
                       <div class="row">
                        <div class="col">
                          <h1 class="text-uppercase">
                            Painel -> Instituições
                          </h1>
                        </div>
                        <div class="col d-flex">
                            <a href="{% url 'cursos_empresariais:administrativo2' %}" class="btn btn-dark ms-auto my-auto">
                              PAINEL
                            </a>
                        </div>
                       </div>
                        <div class="row px-2 pt-2 d-flex">
                            <div class="col px-0 painel">
                                <a href="{% url 'cursos_empresariais:cadastrar_categoria' %}" {% if CADASTRAR == 'NOVO' %}class="btn disabled ativo"{% endif %}><i class="fa-solid fa-plus me-3"></i>-----</a>
                                <a href="{% url 'cursos_empresariais:adm_categorias_listar' %}"  {% if CADASTRAR != 'NOVO' %}class="ativo"{% endif %}><i class="fa-regular fa-file-lines me-3"></i>LISTAR/EDITAR Instituições</a>
                            </div>
                        </div>
                        <div class="row">
                          <div class="col-12 pt-4">
                            <form class="row px-2" method="POST">
                              <div class="col-12">
                                <div class="w-100 h-100">
                                  {% csrf_token %}
                                  {% bootstrap_form form %}
                                </div>
                              </div>                              
                              
                              <button class="btn btn-outline-primary mt-3">
                                  {{CADASTRAR}}
                              </button>
                          </form>
                          </div>                          
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</div>

  <script>

  



   
  </script>
{% endblock %}

cursos_empresariais/templates/adm/instituicoes/adm_instituicoes_listar.html
{% extends 'template.html' %}
{% load bootstrap5 %}
{% load static%}
{% block title %}BEM VINDO - CURSOS LIVRES{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/administrativo.css' %}">

{% endblock %}
{% block nav %}
{% include 'nav_empreendedor.html' %}
{% endblock %}
{% block administrativo %}fw-bold{% endblock %}
{% block main %}
<div class="row">
    <div class="col d-flex py-5"> 
        <div class="row w-100">
            <div class="col-10 pb-4 m-auto bg-white">
                             
                <div class="row">
                    <div class="col text-dark px-4 pt-4">
                       <div class="row">
                        <div class="col">
                          <h1 class="text-uppercase">
                            Painel -> <b>Instituições</b>
                          </h1>
                        </div>
                        <div class="col d-flex">
                            <a href="{% url 'cursos_empresariais:administrativo2' %}" class="btn btn-dark ms-auto my-auto">
                              PAINEL
                            </a>
                        </div>
                       </div>
                        <div class="row px-2 pt-2 d-flex">
                            <div class="col px-0 painel">
                              <a href="{% url 'cursos_empresariais:adm_cadastrar_instituicao' %}"><i class="fa-solid fa-plus me-3"></i>Nova Instituição</a>
                              <a href="" class="btn ativo disabled"><i class="fa-regular fa-file-lines me-3"></i>---</a>
                            </div>
                        </div>
                        <div class="row">
                          <div class="col-12 pt-4">
                            <form class="row px-2" method="POST">
                              <div class="col-12">
                                {% comment %} <div class="d-flex w-100">
                                  <select class="form-select" name="acao" id="acao">
                                    <option value="0">
                                      Realizar ação em lote
                                    </option>
                                    <option value="1">
                                      Encerrar turmas
                                    </option>
                                  </select>
                                  <button class="btn btn-primary px-3 ms-2">
                                    Ir
                                  </button>
                                </div> {% endcomment %}
                                <div class="w-100 h-100 pt-3 table-responsive">
                                  <table class="table table-striped table-primary">
                                    <thead>

                                      <th>Nome da instituição</th>   
                                      <th>Sigla</th>                                      

                                    </thead>
                                    <tbody>
                                      {% for instituicao in instituicoes %}
                                        <tr>
                                        
                                          <td>{{instituicao.nome}}</td>  
                                          <td>{{instituicao.sigla}}</td>                                          
                                        </tr>
                                      {% endfor %}
                                    </tbody>                                  
                                </table>
                                </div>
                              </div>                                                                                          
                          </form>
                          </div>                          
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</div>


{% endblock %}