api/urls.py
from django import views
from django.urls import path, include
from . import serializer
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from . import views
from rest_framework.authtoken.views import obtain_auth_token
app_name='api'

urlpatterns = [
       path('token/', obtain_auth_token, name="api_token_auth"),
       path('sala-do-empreendedor/get-empresas/', views.Listar_Empresas.as_view()),
       path('cursos/get-interessados/<int:curso_id>/', views.AlunosInteressadosView.as_view(), name='listar_alunos_interessados'),
       path('cursos/get-cursos/', views.Listar_Cursos.as_view(), name='listar_cursos'),
]

iluminacao/urls.py
from django.urls import path
from . import views
 
app_name='iluminacao'
urlpatterns = [
    path('os/reset/conclusao/123654/', views.mudadados, name='mudados'),
    path('os/alterar_equipes/123456/', views.alterar_equipes, name='alterar_equipes'),

    path('', views.os_index, name='os_index'),
    path('finalizados/', views.os_finalizados, name='os_finalizados'),
    path('painel/', views.os_painel, name='os_painel'),
    path('os/', views.add_os, name='add_os'),
    path('os/contar-os/', views.contagem_os, name='contagem_os'),
    path('os/salvar-contagem/', views.salvar_contagem_os, name='salvar_contagem_os'),

    path('os/painel/<id>/', views.detalhes_os, name='detalhes_os'),
    path('os/painel/<id>/pontos', views.pontos_os, name='pontos_os'),
    path('imprimir/', views.os_index, name='imprimir_nada'),
    path('imprimir/<ids>/', views.imprimir_varias_os, name='imprimir_varias'),
    path('imprimir-todas/', views.imprimir_todas_os, name='imprimir_todas'),
    path('os/painel/<id>/imprimir/', views.imprimir_os, name='imprimir'),
    path('os/painel/<id>/alterar_status/<opcao>', views.change_status_os, name='change_status_os'),
    path('os/painel/<id>/alterar_prioridade/<opcao>', views.change_prioridade_os, name='change_prioridade_os'),
    path('os/painel/<id>/atender', views.atender_os, name='atender_os'),

    path('os/kpi', views.graficos, name='kpi'),
    path('os/kpi/ver-mais/<tipo>/<subtipo>/', views.graficos_ver_mais, name='kpi_ver_mais'),
    path('funcionario', views.funcionarios_listar, name='funcionarios'),
    path('funcionario/cadastrar/', views.funcionario_cadastrar, name='cadastrar funcionario'),
    path('funcionario/editar/<id>/', views.funcionario_editar, name='editar funcionario'),
    path('funcionario/deletar/<id>/', views.funcionario_deletar, name='deletar funcionario'),

    # path('gerar-relatorio/', views.gerar_relatorio_view, name='gerar_relatorio'),
    path('os/painel/<id>/equipe/', views.atribuir_equipe, name='atribuir equipe')
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('', include('desenvolve_nf.urls')),
    path('api/', include('api.urls')),
    path('ciencia-e-tecnologia/', include('cursos.urls')),    
    path('chat/', include('chat.urls')),
    path('sala-do-empreendedor/', include('sala_do_empreendedor.urls')),
    path('sala-do-empreendedor/', include('cursos_empresariais.urls')),
    path('sala-do-empreendedor/', include('cursos_profissionais.urls')),
    # path('senha-facil/', include('senhas_facil.urls')),
    path('administracao/', include('administracao.urls')),    
    path('django/', admin.site.urls),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iluminacao/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import OrdemDeServico, Funcionario_OS, OS_ext, OS_Linha_Tempo
from autenticacao.models import Pessoa
from django.contrib.auth.models import Group
from django.forms import ModelChoiceField

class OS_Form(ModelForm):    
    
    class Meta:
        model = OrdemDeServico
        widgets = {
            'tipo': forms.Select(attrs={'readonly': True}),
        }
        exclude = ['numero', 'dt_inclusao', 'dt_alteracao','dt_execucao', 'observacao_pontos','atendente', 'dt_conclusao', 'prioridade', 'status', 'contribuinte', 'pontos_atendidos', 'cadastrado_por']


class OS_Form_Ponto(ModelForm):    
        
    class Meta:
        model = OrdemDeServico       
        widgets={
         'dt_execucao': forms.DateInput(attrs={'class': 'form-control', 'type':'date'}),
         }
        fields = ['pontos_atendidos', 'observacao_pontos', 'dt_execucao']

class PessoaChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.nome
    
class Funcionario_Form(ModelForm):

    pessoa = PessoaChoiceField(queryset=Pessoa.objects.none(), label='Selecione uma pessoa')

    def __init__(self, *args, **kwargs):
        grupo = kwargs.pop('grupo', None) or Group.objects.get(name='os_funcionario')
        super().__init__(*args, **kwargs)
        if grupo:
            self.fields['pessoa'].queryset = Pessoa.objects.filter(user__groups=grupo)

    class Meta:
        model = Funcionario_OS
        widgets = {'tipo_os': forms.HiddenInput()}
        fields = ['pessoa', 'nivel', 'tipo_os']

class Funcionario_Form_editar(ModelForm):

    pessoa = PessoaChoiceField(queryset=Pessoa.objects.none(), label='Selecione uma pessoa')

    def __init__(self, *args, **kwargs):
        grupo = kwargs.pop('grupo', None) or Group.objects.get(name='os_funcionario')
        super().__init__(*args, **kwargs)
        if grupo:
            self.fields['pessoa'].queryset = Pessoa.objects.filter(user__groups=grupo)

    class Meta:
        model = Funcionario_OS
        widgets = {'tipo_os': forms.HiddenInput()}
        fields = ['pessoa', 'nivel', 'tipo_os']


class Equipe_Form(ModelForm):
    class Meta:
        model = OS_ext
        widgets = {
            'equipe': forms.CheckboxSelectMultiple(),
            'os': forms.HiddenInput()

        }        
        exclude=[]

class NovaMensagemForm(forms.ModelForm):
    class Meta:
        model = OS_Linha_Tempo
        fields = ['os', 'pessoa', 'mensagem', 'anexo']
        widgets = {
            'os': forms.HiddenInput(),
            'pessoa': forms.HiddenInput(),
            'mensagem': forms.Textarea(attrs={'class': 'form-control h-100', 'rows': 6}),
            'anexo': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

iluminacao/views.py
from django.shortcuts import render, redirect
from .forms import *
from autenticacao.models import Pessoa
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.apps import apps
from .models import *
from settings.decorators import group_required
from django.contrib.auth.models import Group
from datetime import datetime
from django.db.models import Case, When, Count, Sum, IntegerField

from django.http import HttpResponse
from openpyxl import Workbook
from datetime import datetime, timedelta
from django.utils import timezone
from .custom import month_translate
from django.db import connection, models

STATUS_CHOICES=(
        ('0','Novo'),
        ('1','Aguardando'),
        ('2','Em execução'),
        ('f','Finalizado')
    )
PRIORIDADE_CHOICES=(
        ('0','Normal'),
        ('1','Moderada'),
        ('2','Urgente'),
    )

@group_required('os_acesso')
def index(request):
    return render(request, 'os_index.html')
# from .functions import get_os_stats

# def relatorio_mensal(request, month, year):
#     stats = get_os_stats(month, year)
    
#     context = {
#         'os_by_bairro': stats['os_by_bairro'],
#         'total_os': stats['total_os'],
#         'avg_os': stats['avg_os'],
#         'median_os': stats['median_os'],
#         'points_by_bairro': stats['points_by_bairro'],
#         'difference': stats['difference']
#     }
    
#     return render(request, 'relatorio_mensal.html', context)

@login_required
@group_required('os_acesso')
def os_painel(request):    
    # meses = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']
    # bairros = OrdemDeServico.objects.values_list('bairro', flat=True).distinct()
    # data = []  

    # for bairro in bairros:
    #     total=OrdemDeServico.objects.filter(bairro=bairro, status__in=['0', '1', '2'], dt_solicitacao__year='2023').count()
    #     os_por_mes = OrdemDeServico.objects.filter(bairro=bairro, status__in=['0', '1', '2'], dt_solicitacao__year='2023').annotate(
    #         jan=Count('id', filter=models.Q(dt_solicitacao__month=1)),
    #         fev=Count('id', filter=models.Q(dt_solicitacao__month=2)),
    #         mar=Count('id', filter=models.Q(dt_solicitacao__month=3)),
    #         abr=Count('id', filter=models.Q(dt_solicitacao__month=4)),
    #         mai=Count('id', filter=models.Q(dt_solicitacao__month=5)),
    #         jun=Count('id', filter=models.Q(dt_solicitacao__month=6)),
    #         jul=Count('id', filter=models.Q(dt_solicitacao__month=7)),
    #         ago=Count('id', filter=models.Q(dt_solicitacao__month=8)),
    #         set=Count('id', filter=models.Q(dt_solicitacao__month=9)),
    #         out=Count('id', filter=models.Q(dt_solicitacao__month=10)),
    #         nov=Count('id', filter=models.Q(dt_solicitacao__month=11)),
    #         dez=Count('id', filter=models.Q(dt_solicitacao__month=12)),
    #     ).values('jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez')

    #     dt={'bairro': bairro, 'mes': os_por_mes, 'total': total}
    #     if not any(item['bairro'] == bairro for item in data):
    #         data.append(dt)
    # bairros = (
    #     OrdemDeServico.objects
    #     .filter(status__in=['0', '1', '2'], dt_solicitacao__year='2023')
    #     .values('bairro')
    #     .annotate(
    #         total=Count('id'),
    #         jan=Sum(models.Case(models.When(dt_solicitacao__month=1, then=1), default=0, output_field=models.IntegerField())),
    #         fev=Sum(models.Case(models.When(dt_solicitacao__month=2, then=1), default=0, output_field=models.IntegerField())),
    #         mar=Sum(models.Case(models.When(dt_solicitacao__month=3, then=1), default=0, output_field=models.IntegerField())),
    #         abr=Sum(models.Case(models.When(dt_solicitacao__month=4, then=1), default=0, output_field=models.IntegerField())),
    #         mai=Sum(models.Case(models.When(dt_solicitacao__month=5, then=1), default=0, output_field=models.IntegerField())),
    #         jun=Sum(models.Case(models.When(dt_solicitacao__month=6, then=1), default=0, output_field=models.IntegerField())),
    #         jul=Sum(models.Case(models.When(dt_solicitacao__month=7, then=1), default=0, output_field=models.IntegerField())),
    #         ago=Sum(models.Case(models.When(dt_solicitacao__month=8, then=1), default=0, output_field=models.IntegerField())),
    #         set=Sum(models.Case(models.When(dt_solicitacao__month=9, then=1), default=0, output_field=models.IntegerField())),
    #         out=Sum(models.Case(models.When(dt_solicitacao__month=10, then=1), default=0, output_field=models.IntegerField())),
    #         nov=Sum(models.Case(models.When(dt_solicitacao__month=11, then=1), default=0, output_field=models.IntegerField())),
    #         dez=Sum(models.Case(models.When(dt_solicitacao__month=12, then=1), default=0, output_field=models.IntegerField()))
    #     )
    # )

    # data = []
    # for bairro in bairros:
    #     bairro_data = {
    #         'bairro': bairro['bairro'],
    #         'mes': {
    #             'jan': bairro['jan'],
    #             'fev': bairro['fev'],
    #             'mar': bairro['mar'],
    #             'abr': bairro['abr'],
    #             'mai': bairro['mai'],
    #             'jun': bairro['jun'],
    #             'jul': bairro['jul'],
    #             'ago': bairro['ago'],
    #             'set': bairro['set'],
    #             'out': bairro['out'],
    #             'nov': bairro['nov'],
    #             'dez': bairro['dez'],
    #         },
    #         'total': bairro['total']
    #     }
    #     data.append(bairro_data)

    # query = '''
    # SELECT
    #     bairro,
    #     COUNT(*) AS total,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 1) AS `jan`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 2) AS `fev`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 3) AS `mar`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 4) AS `abr`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 5) AS `mai`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 6) AS `jun`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 7) AS `jul`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 8) AS `ago`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 9) AS `et`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 10) AS `out`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 11) AS `nov`,
    #     SUM(EXTRACT(MONTH FROM dt_solicitacao) = 12) AS `dez`
    # FROM
    #     iluminacao_ordemdeservico
    # WHERE
    #     bairro IS NOT NULL
    #     AND status IN ('0', '1', '2')
    #     AND YEAR(dt_solicitacao) = 2023
    # GROUP BY
    #     bairro
    # '''

    # with connection.cursor() as cursor:
    #     cursor.execute(query)
    #     rows = cursor.fetchall()

    # data = []
    # for row in rows:
    #     bairro = row[0]
    #     total = row[1]
    #     meses = row[2:]
    #     os_por_mes = {meses[i]: value for i, value in enumerate(meses)}
    #     data.append({'bairro': bairro, 'mes': os_por_mes, 'total': total})

    # query = """
    #     SELECT (SELECT COUNT(*) FROM iluminacao_ordemdeservico WHERE status!='f' and bairro = main.bairro GROUP BY bairro) as total, bairro, (SELECT COUNT(dt_solicitacao) FROM iluminacao_ordemdeservico GROUP BY bairro), 
    #         CASE
    #             WHEN strftime('%m', dt_solicitacao) = '01' THEN 'Janeiro'
    #             WHEN strftime('%m', dt_solicitacao) = '02' THEN 'Fevereiro'
    #             WHEN strftime('%m', dt_solicitacao) = '03' THEN 'Março'
    #             WHEN strftime('%m', dt_solicitacao) = '04' THEN 'Abril'
    #             WHEN strftime('%m', dt_solicitacao) = '05' THEN 'Maio'
    #             WHEN strftime('%m', dt_solicitacao) = '06' THEN 'Junho'
    #             WHEN strftime('%m', dt_solicitacao) = '07' THEN 'Julho'
    #             WHEN strftime('%m', dt_solicitacao) = '08' THEN 'Agosto'
    #             WHEN strftime('%m', dt_solicitacao) = '09' THEN 'Setembro'
    #             WHEN strftime('%m', dt_solicitacao) = '10' THEN 'Outubro'
    #             WHEN strftime('%m', dt_solicitacao) = '11' THEN 'Novembro'
    #             WHEN strftime('%m', dt_solicitacao) = '12' THEN 'Dezembro'
    #             ELSE NULL
    #     END AS nome_mes
    #     FROM iluminacao_ordemdeservico as main
    #     WHERE status != 'f'
    #     GROUP BY bairro
    #     ORDER BY bairro;
    #     """
    query = """
        SELECT (SELECT COUNT(*) FROM iluminacao_ordemdeservico WHERE status!='f' and bairro = main.bairro GROUP BY bairro) as total,bairro, 
        COUNT(dt_solicitacao), 
        MONTHNAME(dt_solicitacao) AS nome_mes 
        FROM iluminacao_ordemdeservico as main 
        WHERE status != 'f' 
        GROUP BY bairro, MONTH(dt_solicitacao) 
        ORDER BY bairro; 
    """
    with connection.cursor() as cursor:
        cursor.execute(query)
        results = cursor.fetchall()

    # print(results)
    resultados_formatados = []
    for row in results:
        total, bairro, count_dt_solicitacao, nome_mes = row
        resultado_dict = {
            'bairro': bairro,
            'total': total,
            'mes': nome_mes,
            'total_por_mes': count_dt_solicitacao
        }
        resultados_formatados.append(resultado_dict)

    bairros=[]
    for result in resultados_formatados:  
        bairros.append(result['bairro'])
    bairros_ = list(set(bairros))

    resultados_agrupados = []
    for b in bairros_:
        resultados_agrupados.append(
            {'bairro': b}
        )

    for result in resultados_formatados:
        bairro = result['bairro']
        mes = result['mes']
        total_por_mes = result['total_por_mes']
        total = result['total']
        # print(bairro, mes, total_por_mes, total)
        for i in resultados_agrupados:
            # print(i)
            if i['bairro'] == bairro:
                i[mes]=total_por_mes

iluminacao/templates/iluminacao/adicionar_ext.html
{% extends 'template.html' %}
{% load bootstrap5 %}
{% load static%}
{% block title %}Adicionar{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/almoxarifado.css' %}">

{% endblock %}
{% block os %}fw-bolder{% endblock %}
{% block main %}
<div class="row">
  <div class="col d-flex py-5"> 
        <div class="row w-100">
            <div class="col-10 pb-4 m-auto bg-white">       
                <div class="row">
                    <div class="col px-4">                        
            
                        <div class="pt-4 px-2">
                            <form method="POST">
                                <h2>Atribuir equipe</h2>
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                <button type="submit" class="btn btn-primary">
                                Enviar
                                </button>
                            </form>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>    
  </div>
</div>
<!-- MODAL --> 
  <script>
       function icpf(v){
        v=v.replace(/\D/g,"")                    //Remove tudo o que nao e digito
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o segundo e terceiro digitos
        v=v.replace(/(\d{3})(\d)/,"$1.$2")       //Coloca um ponto entre o quinto e o sexto digitos
        v=v.replace(/(\d{3})(\d)/,"$1-$2")       //Coloca um ponto entre o quinto e o sexto digitos
        // v=v.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/, "$1.$2.$3/$4-$5")
        return v
    }
    function mascara(o,f){
        v_obj=o
        v_fun=f
        setTimeout("execmascara()",1)
    }            
    function execmascara(){
        v_obj.value=v_fun(v_obj.value)
    }
    function itel(v){
        if (v.length==15){
            v=v.replace(/\D/g,"")                 //Remove tudo o que nao e digito
            v=v.replace(/^(\d\d)(\d)/g,"($1) $2") //Coloca parenteses em volta dos dois primeiros digitos
            v=v.replace(/(\d{5})(\d)/,"$1-$2")  
        }else{
            v=v.replace(/\D/g,"")                 //Remove tudo o que nao e digito
            v=v.replace(/^(\d\d)(\d)/g,"($1) $2") //Coloca parenteses em volta dos dois primeiros digitos
            v=v.replace(/(\d{4})(\d)/,"$1-$2")    // 
        }
        return v
    }

    
    document.getElementById('os_painel').classList.add('s-nav-active');

  </script>
{% endblock %}

iluminacao/templates/iluminacao/graficos copia.html
{% extends 'template.html' %}
{% load bootstrap5 %}
{% load static%}
{% block nav %}
{% include 'nav_os.html' %}
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/almoxarifado.css' %}">
{% endblock %}
{% block os %}fw-bolder{% endblock %}
{% block main %}
<div class="row">
  <div class="col d-flex py-5"> 
        <div class="row w-100">
            <div class="col-10 pb-5 m-auto bg-white" style="border-radius: 30px;">                           
                <div class="row">
                    <div class="col px-4">                                                
                        <div class="px-2 pt-4 d-flex">
                        <h2 style="display: inline;">Indicadores</h2>                        
                        </div>                    
                    </div>
                </div>  
                <div class="row">
                  <div class="col d-flex pb-4">
                    <div href="https://www.cecierj.edu.br/" class="card-universidade btn  me-1 ms-auto d-flex flex-column">
                      Finalizados:
                      <h1>{{finalizados}}</h1>
                    </div>
                    <div href="http://www.cefet-rj.br/" class="card-universidade btn  ms-1 me-auto d-flex flex-column">
                      Não finalizados:
                      <h1>{{nao_finalizados}}</h1>
                    </div>  
                  </div>
                </div>                
                <div class="row">
                  <div class="col d-flex">
                    <div class="mx-auto">
                      <div id="chart_div"></div>                         
                      <p class="text-center">
                        <a href="{% url 'iluminacao:kpi_ver_mais' 'pontos-por-bairro' 'exibir' %}">
                          Ver mais
                        </a>                 
                      </p>
                    </div>                    
                  </div>              
                </div>
                <div class="row">
                  <div class="col d-flex">
                    <div class="mx-auto">
                      <div id="chart_div2"></div>                    
                      <p class="text-center">
                        <a href="{% url 'iluminacao:kpi_ver_mais' 'os-por-bairro' 'exibir' %}">
                          Ver mais
                        </a>                 
                      </p>
                    </div>
                  </div>              
                </div>
                <div class="row">
                  <div class="col d-flex">
                    <div class="mx-auto">
                      <div id="chart_div3"></div>  
                      <p class="text-center">
                        <a href="{% url 'iluminacao:kpi_ver_mais' 'pontos-por-funcionario' 'exibir' %}">
                          Ver mais
                        </a>                 
                      </p>                  
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col d-flex">
                    <div class="mx-auto">
                      <div id="chart_div4"></div>  
                      <p class="text-center">
                        <a href="#">
                          Ver mais
                        </a>                 
                      </p>                  
                    </div>
                  </div>
                </div>
                                               
                <style>
                  .card-universidade{                    
                    display: flex;
                    background-color: white;
                    width: 300px;
                    height: 110px;
                    border-radius: 30px;          
                    color: rgb(59, 59, 59);
                    border-color: rgb(255, 255, 255);
                    box-shadow: 0px 10px 15px -3px rgba(0,0,0,0.1);          
                    padding-top: 20px;
                    padding-bottom: 20px;
                  }                
                  .card-universidade img{
                    max-height: 100px;
          
                  }
                </style>
                </div>
            </div>
        </div>    
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  document.getElementById('os_painel').classList.add('s-nav-active');  
</script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">

  // Load the Visualization API and the corechart package.
  google.charts.load('current', {'packages':['corechart']});

  // Set a callback to run when the Google Visualization API is loaded.
  google.charts.setOnLoadCallback(drawChart);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Bairro');
    data.addColumn('number', 'Pontos');
    data.addRows([
      {% for item in pontos_por_bairro %}
      ['{{item.bairro}}', {{item.total}}],
      {% endfor %}
    ]);

    // Set chart options
    var options = {'title':'Pontos por bairro',
                   'width':800,
                   'height':500};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>
<script type="text/javascript">

  // Set a callback to run when the Google Visualization API is loaded.
  google.charts.setOnLoadCallback(drawChart2);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart2() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Bairro');
    data.addColumn('number', 'OS');
    data.addRows([
      {% for item in os_por_bairro %}
      ['{{item.bairro}}', {{item.total}}],
      {% endfor %}
    ]);

    // Set chart options
    var options = {'title':'OS por bairro',
                   'width':800,
                   'height':500};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.BarChart(document.getElementById('chart_div2'));
    chart.draw(data, options);
  }
</script>
<script type="text/javascript">

  // Set a callback to run when the Google Visualization API is loaded.
  google.charts.setOnLoadCallback(drawChart3);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart3() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Funcionário');
    data.addColumn('number', 'OS');
    data.addRows([
      {% for item in pontos_por_funcionario %}
      ['{{item}}', {{item.total_pontos}}],
      {% endfor %}
    ]);

    // Set chart options
    var options = {'title':'Pontos do Funcionario',
                   'width':800,
                   'height':500};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.BarChart(document.getElementById('chart_div3'));
    chart.draw(data, options);
  }
</script>
<script type="text/javascript">

  // Set a callback to run when the Google Visualization API is loaded.
  google.charts.setOnLoadCallback(drawChart4);

  // Callback that creates and populates a data table,
  // instantiates the pie chart, passes in the data and
  // draws it.
  function drawChart4() {

    // Create the data table.
    var data = new google.visualization.DataTable();
    data.addColumn('string', 'Funcionário');
    data.addColumn('number', 'Quantidade de bairros atendidos');
    data.addRows([
      {% for item in os_por_funcionario %}
      ['{{item}}', {{item.total_os}}],
      {% endfor %}
    ]);

    // Set chart options
    var options = {'title':'Bairros por Funcionario',
                   'width':800,
                   'height':500};

    // Instantiate and draw our chart, passing in some options.
    var chart = new google.visualization.BarChart(document.getElementById('chart_div4'));
    chart.draw(data, options);
  }
</script>
{% endblock %}

iluminacao/templates/iluminacao/relatorio_mensal.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <title>Relatório Mensal</title>
    <style>
        /* Estilização CSS */
        body { font-family: Arial, sans-serif; }
        h1 { text-align: center; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 10px; border: 1px solid #ddd; text-align: left; }
        th { background-color: #f4f4f4; }
    </style>
</head>
<body>
    <h1>Relatório Mensal - {{ month }}/{{ year }}</h1>

    <h2>OS por Bairro</h2>
    <table>
        <thead>
            <tr>
                <th>Bairro</th>
                <th>Total de OS</th>
            </tr>
        </thead>
        <tbody>
            {% for item in os_by_bairro %}
            <tr>
                <td>