api/urls.py
from django import views
from django.urls import path, include
from . import serializer
# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from . import views
from rest_framework.authtoken.views import obtain_auth_token
app_name='api'

urlpatterns = [
       path('token/', obtain_auth_token, name="api_token_auth"),
       path('sala-do-empreendedor/get-empresas/', views.Listar_Empresas.as_view()),
       path('cursos/get-interessados/<int:curso_id>/', views.AlunosInteressadosView.as_view(), name='listar_alunos_interessados'),
       path('cursos/get-cursos/', views.Listar_Cursos.as_view(), name='listar_cursos'),
]

sala_do_empreendedor/urls.py
from django.urls import path
from . import views
 
app_name='empreendedor'
urlpatterns = [
    path('importar-empresas/', views.importar_empresas, name='importar_empresas'),
    path('', views.index, name='index'),
    path('cursos/', views.cursos, name='cursos'),
    
    path('consultar-protocolo', views.consultar_protocolo, name='consultar_protocolo'),
    
    path('conheca-nossa-sala', views.conheca_nossa_sala, name='conheca_nossa_sala'),
    
    path('minha-empresa', views.minha_empresa, name='minha_empresa'),
    path('minha-empresa/pca/', views.pca_list, name='pca'),
    path('minha-empresa/pca/download/', views.pca_list_excel_download, name='pca_download'),
    path('minha-empresa/cadastrar', views.cadastrar_empresa, name='cadastrar_empresa'),
    path('minha-empresa/<id>/editar/', views.editar_empresa, name='editar_empresa'),
    path('minha-empresa/<int:empresa_id>/perfil/', views.perfil_empresa, name='perfil_empresa'),
    path('minha-empresa/<id>/vitrine/', views.minha_vitrine, name='minha_vitrine'),
    path('minha-empresa/<id>/vitrine/alterar-logo', views.enviar_ou_trocar_logo, name='enviar_ou_trocar_logo'),
    path('minha-empresa/<id>/cadastrar-vitrine', views.cadastrar_vitrine, name='cadastrar_vitrine'),
    path('minha-empresa/<id>/cadastrar-vitrine/<foto_id>/excluir/', views.vitrine_excluir_produto, name='excluir_produto'),
    path('minha-empresa/<id>/vitrine/cadastrar-produto/', views.casdastrar_produto, name='cadastrar_produto'),
    path('faccao-legal/', views.faccao_legal, name='faccao_legal'),
    path('faccao-legal/cadastrar/', views.cadastrar_faccao_legal, name='cadastrar_faccao_legal'),
    path('faccao-legal/apagar/', views.apagar_faccao, name='apagar_faccao'),
    path('faccao-legal/exportar/', views.export_faccoes, name='exportar_faccao'),
    path('vitrine-virtual', views.vitrine_virtual, name='vitrine_virtual'),
    path('pesquisar-empresas', views.pesquisar_empresas, name='paginas_pesquisa-empresa'),
    path('cadastro-fornecedores-e-compras-publicas', views.cadastro_fornecedores_e_compras_publicas, name='compras_publicas'),
    
    path('quero-ser-mei', views.quero_ser_mei, name='quero_ser_mei'),
    path('quero-ser-mei/por-que-ser-mei', views.por_que_ser_mei, name='por_que_ser_mei'),
    path('quero-ser-mei/o-que-voce-precisa-saber-antes-de-se-tornar-um-mei', views.o_que_precisa_saber_para_ser_mei, name='o_que_precisa_saber_para_ser_mei'),
    path('quero-ser-mei/jornada-empreendedora', views.jornada_empreendedora, name='jornada_empreendedora'),
    path('quero-ser-mei/documentosNecessarios', views.documentosNecessarios, name='documentosNecessarios'),
    path('quero-ser-mei/quaisAsOcupacoesQuePodemSerMei', views.quaisAsOcupacoesQuePodemSerMei, name='quaisAsOcupacoesQuePodemSerMei'),
    path('quero-ser-mei/dicasDeSegurancaDaVigilanciaSanitaria', views.dicasDeSegurancaDaVigilanciaSanitaria, name='dicasDeSegurancaDaVigilanciaSanitaria'),
    path('quero-ser-mei/dicasDeSegurançaDoCorpoDeBombeiros', views.dicasDeSegurançaDoCorpoDeBombeiros, name='dicasDeSegurançaDoCorpoDeBombeiros'),
    path('quero-ser-mei/dicasDeMeioAmbiente', views.dicasDeMeioAmbiente, name='dicasDeMeioAmbiente'),
    path('quero-ser-mei/prepareSe', views.prepareSe, name='prepareSe'),
    path('quero-ser-mei/transportadorAutonomoDeCargas', views.transportadorAutonomoDeCargas, name='transportadorAutonomoDeCargas'),
    path('quero-ser-mei/direitosEObrigacoes', views.direitosEObrigacoes, name='direitosEObrigacoes'),
    path('quero-ser-mei/registrocadastur', views.registrocadastur, name="registrocadastur"),
   
    path('ja-sou-mei', views.ja_sou_mei, name='ja_sou_mei'),
    path('ja-sou-mei/emissaoDeComprovante', views.emissaoDeComprovante, name="emissaoDeComprovante"),
    path('ja-sou-mei/atualizacaoCadastral', views.atualizacaoCadastral, name="atualizacaoCadastral"),
    path('ja-sou-mei/capacita', views.capacita, name="capacita"),
    path('ja-sou-mei/notaFiscal', views.notaFiscal, name="notaFiscal"),
    path('ja-sou-mei/relatorioMensal', views.relatorioMensal, name="relatorioMensal"),
    path('ja-sou-mei/pagamentoDeContribuicaoMensal', views.pagamentoDeContribuicaoMensal, name="pagamentoDeContribuicaoMensal"),
    path('ja-sou-mei/solucoesFinanceiras', views.solucoesFinanceiras, name="solucoesFinanceiras"),
    path('ja-sou-mei/certidoesEComprovantes', views.certidoesEComprovantes, name="certidoesEComprovantes"),
    path('ja-sou-mei/declaracaoAnualDeFaturamento', views.declaracaoAnualDeFaturamento, name="declaracaoAnualDeFaturamento"),
    path('ja-sou-mei/dispensaDeAlvara', views.dispensaDeAlvara, name="dispensaDeAlvara"),
    
    path('abertuda-de-empresa', views.abertura_de_empresa, name='abertura_de_empresa'),
    path('iss-autonomos', views.iss_autonomos, name='iss_autonomos'),
    path('legislacao', views.legislacao, name='legislacao'),
    
    path('admin/', views.sala_do_empreendedor_admin, name='admin'),
    path('admin/mapeamento-empresa-e-fornecedores', views.mapeamento_empresa_e_fornecedores, name='mapeamento_empresa_e_fornecedores'),
    path('faccao-legal/cadastrar/checkcnpj/', views.checkCNPJ, name='checkcnpj'),
    path('admin/cadastrar-profissao/', views.cadastrar_profissao, name='cadastrar_profissao'),
    
    #OPORTUNIDADES
    path('oportunidade-de-negocios', views.oportunidade_de_negocios, name='oportunidade'),
    path('oportunidade-de-negocios/natal-do-artesao/checkcpf/', views.checkCPFArtesao, name='natal_artesao_check_cpf'),
    path('oportunidade-de-negocios/natal-do-artesao/', views.natal_artesao, name='natal_artesao'),
    path('oportunidade-de-negocios/dados/', views.oportunidade_de_negocios_dados, name='dados_oportunidades'),
    path('novas-oportunidades/', views.novas_oportunidades, name='novas_oportunidades'),
    path('novas-oportunidades/exportar/', views.export_novas_oportunidades, name='novas_oportunidades_exportar'),
    path('novas-oportunidades/reuniao-sebrae/', views.redirecionamento_novas_oportunidades, name='reuniao_sebrae'),
    #PROCESSOS
    # Opções
    path('iss-autonomos', views.iss_autonomos, name='iss_autonomos'),
    path('consultar-processos/', views.consultar_processos, name='consultar_processos'),
    # Consulta do processo
    path('adm/processos-digitais/', views.processos_digitais_admin, name='processos_digitais_admin'),
    path('adm/processos-digitais/concluidos/', views.processos_concluidos, name='processos_concluidos'),
    path('adm/processos-digitais/licenca-sanitaria/', views.processo_sanitario, name='processo_sanitario'),
    path('adm/processos-digitais/concluidos/sanitario/', views.processos_concluidos_sanitario, name='novo_andamento_processo_sanitario_admin'),    
    path('consultar-processos/desenvolve/', views.meus_processos, name='listar_processos'),
    # Criar novo processo
    path('processos/criar-novo/', views.novo_processo, name='novo_processo'),
    path('processos-digitais/requerimento-ISSQ/', views.requerimento_ISSQN, name='requerimento_issqn'),
    path('processos/criar-novo/requerimento-iss/', views.em_construcao, name='requerimento_iss'),
    # path('processos/criar-novo/requerimento-iss/', views.requerimento_iss, name='requerimento_iss'),
    path('adm/processos/criar-novo/requerimento-iss/', views.requerimento_iss_admin, name='requerimento_iss_admin'),
    # Envio de documentos requeridos
    path('processos/criar-novo/envio-de-documentos/<n_protocolo>/', views.requerimento_documentos, name='requerimento_iss_doc'),
    path('processos/criar-novo/uniprofissional/envio-de-documentos/<n_protocolo>/', views.requerimento_ISSQN_doc, name='requerimento_issqn_doc'),
    # Coonsulta do processo
    path('adm/processos-digitais/andamento/<id>/', views.andamento_processo_admin, name='andamento_processo_admin'),    
    path('adm/processos-digitais/andamento/licenca-sanitaria/<id>/', views.andamento_processo_sanitario, name='andamento_processo_sanitario'),    
    path('adm/processos-digitais/andamento/licenca-ambiental/<id>/', views.andamento_processo_ambiental, name='andamento_processo_ambiental'),    
    path('processos-digitais/<protocolo>/', views.andamento_processo, name='andamento_processo'),
    # Dar andamento no processo
    path('adm/processos-digitais/<id>/novo-andamento/', views.novo_andamento_processo, name='novo_andamento_processo_admin'),
    path('adm/processos-digitais/<id>/novo-andamento/sanitario/', views.novo_andamento_processo_sanitario, name='novo_andamento_processo_sanitario_admin'),
    path('adm/processos-digitais/<id>/novo-andamento/ambiental/', views.novo_andamento_processo_ambiental, name='novo_andamento_processo_ambiental_admin'),
    # Atualizar documento do processo
    path('processos-digitais/<protocolo>/att-doc/<doc>', views.atualizar_documento_processo, name='atualizar_documento_processo'),
    
    
    
    path('checkCPF/', views.checkCPF, name='checkCPF'),
    path('checkProfissao/', views.checkProfissao, name='checkProfissao'),
    path('muda-status/', views.mudaStatus, name='mudaStatus'),
    path('muda-status-iss/', views.mudaStatus_ISS, name='mudaStatusISS'),
    path('muda-status-rg/', views.mudaStatusRG, name='mudaStatusRG'),
    path('muda-status-comprovante/', views.mudaStatusComprovante, name='mudaStatusComprovante'),
    path('muda-status-Ccertificado/', views.mudaStatusCertificado, name='mudaStatusCertificado'),
    path('muda-status-licenca/', views.mudaStatusLicenca, name='mudaStatusLicenca'),
    path('muda-status-licenca/<tipo>', views.mudaStatusLicencaComTipo, name='mudaStatusLicencaComTipo'),
    path('muda-status-espelho/', views.mudaStatusEspelho, name='mudaStatusEspelho'),
    
    # PDDE
    path('adm/pdde/', views.pdde_admin, name='pdde_admin'),
    path('pdde/', views.pdde_index, name='pdde_index'),
    path('pdde/escola/', views.pdde_index_escola, name='pdde_escola'),
    path('pdde/empresa/', views.pdde_index_empresa, name='pdde_empresa'),
    path('pdde/empresa/solicitacao/<hash>/', views.pdde_menu_opcoes_empresa, name='pdde_empresa_menu'),

settings/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('autenticacao.urls')),
    path('', include('desenvolve_nf.urls')),
    path('api/', include('api.urls')),
    path('ciencia-e-tecnologia/', include('cursos.urls')),    
    path('chat/', include('chat.urls')),
    path('sala-do-empreendedor/', include('sala_do_empreendedor.urls')),
    path('sala-do-empreendedor/', include('cursos_empresariais.urls')),
    path('sala-do-empreendedor/', include('cursos_profissionais.urls')),
    # path('senha-facil/', include('senhas_facil.urls')),
    path('administracao/', include('administracao.urls')),    
    path('django/', admin.site.urls),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sala_do_empreendedor/templates/sala_do_empreendedor/credito_facil/emprestimo.html
{% extends 'template.html' %}
{% load static %}
{% load bootstrap5 %}
{% block nav %}
{% include 'nav_empreendedor.html' %}
{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/sala_empreendedor_pages.css' %}">
{% endblock %}
{% block main %}
<!-- Hero Section -->
<section class="service-hero">
  <div class="container pt-4">
    <div class="hero-content-service" data-aos="fade-up">
      <div class="row" data-aos="fade-up">
        <div class="col">
          <a href="{% url 'empreendedor:index' %}" class="back-button">
            <i class="fas fa-arrow-left"></i>
            Voltar
          </a>
        </div>
      </div>
      <h1 class="section-title-service">Solicitação de Linha de Crédito</h1>
      <p class="lead">Intermediação para obtenção de linhas de crédito para MEIs e pequenas empresas</p>
    </div>
  </div>
</section>

<div class="container pb-5">
  <div class="row" data-aos="fade-up">
    <div class="col-lg-8 mx-auto">
      <div class="alert-service">
        <h5 class="fw-bold mb-3">
          <i class="fas fa-info-circle text-primary me-2"></i>
          Como Funciona
        </h5>
        <p class="mb-0">A Prefeitura de Nova Friburgo, por meio da Sala do Empreendedor, está intermediando com diversas instituições a possibilidade de fornecimento de linhas de crédito para MEIs, micro e pequenas empresas. Se esta for uma necessidade para sua empresa, preencha o formulário abaixo e entraremos em contato em breve.</p>
      </div>
      
      <div class="form-container">
        <form method="POST">                
          {% csrf_token %}
          {% bootstrap_form form %}
          <div class="text-center mt-4">
            <button class="btn-service" type="submit">
              <i class="fas fa-paper-plane me-2"></i>
              Enviar Solicitação
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="row mx-auto px-5">
  <script>
    document.getElementById('empreendedor_servicos').classList.add('s-nav-active');
    
    function icnpj(inputValue) {
                    let value = inputValue.replace(/\D/g, ""); // Remove caracteres não numéricos
                    value = value.replace(/(\d{2})(\d)/, "$1.$2"); // Coloca um ponto entre o segundo e o terceiro dígitos
                    value = value.replace(/(\d{3})(\d)/, "$1.$2"); // Coloca um ponto entre o quarto e o quinto dígitos
                    value = value.replace(/(\d{3})(\d)/, "$1/$2"); // Coloca uma barra entre o sétimo e o oitavo dígitos
                    value = value.replace(/(\d{4})(\d{1,2})$/, "$1-$2"); // Coloca um hífen entre o décimo segundo e o décimo terceiro dígitos
                    return value;
                }
    function itel(v){
                    v=v.replace(/\D/g,"")                 //Remove tudo o que nao e digito
                    v=v.replace(/^(\d\d)(\d)/g,"($1) $2") //Coloca parenteses em volta dos dois primeiros digitos
                    console.log(v.length)
                    if (v.length<14){
                      v=v.replace(/(\d{4})(\d)/,"$1-$2")    //Coloca hifen entre o quarto e o quinto digitos
                    }else{
                      v=v.replace(/(\d{4,5})(\d)/,"$1-$2")    //Coloca hifen entre o quarto e o quinto digitos
                    }
                    
                    return v
                }
    function icep(input) {
            input.value = input.value.replace(/\D/g, '');

            // Verifica se o valor tem pelo menos 5 dígitos
            if (input.value.length > 5) {
            // Insere o traço após o quinto dígito
            input.value = input.value.substring(0, 5) + '-' + input.value.substring(5);
            }
            }
    function mascara(o,f){
                v_obj=o
                v_fun=f
                setTimeout("execmascara()",1)
            }
        
    function execmascara(){
                v_obj.value=v_fun(v_obj.value)
            }
    function findParentDiv(element) {
        var parent = element.parentNode;
        
        // Continue subindo na árvore DOM até encontrar um elemento <div>
        while (parent && parent.nodeName !== 'DIV') {
          parent = parent.parentNode;
        }

        return parent;
      }
    div = findParentDiv(document.getElementById('id_outra_motivacao'))
    div.style.display = 'none'

    function toggleMotivacao(e) {
        if (e.value === 'ou') {
            div.style.display = 'block'
        } else {
            div.style.display = 'none'
        }
    }
    // GAMBIARRA ABAIXO
    function removerElementos() {
          // Seleciona todos os elementos label
          const labels = document.querySelectorAll('label');

          // Itera pelos elementos label
          labels.forEach(function(label) {
              // Verifica se o label contém um input e o texto "---------"
              const input = label.querySelector('input');
              if (input && label.textContent.trim() === '---------') {
                  // Remove o elemento label do DOM
                  findParentDiv(label).remove();
                  // label.remove();
              }
          });
    }
    removerElementos();
  </script>
</div>

<style>
  .border{
    border-color: rgba(146, 146, 146, 0.2) !important;
  }
  label{
    font-weight: bold;
  }
  .checkbox label, .radio label{
    font-weight: normal;
  }
</style>

{% endblock %}
{% block footer %}
{% include 'desenvolve_nf/instagram.html' %}
{% endblock %}